### PR TITLE
Gw

### PR DESCRIPTION
**Pull request by mrYakamoto**

### CODE REVIEW

**Comment by matthutchinson** [comment]
Unfortunately, Array#sample is [only available](http://apidock.com/ruby/Array/sample) in Ruby 1.9+  currently this gem (for legacy reasons) supports Rubies back to `1.8.7`

@mroth - unless you think its OK to drop this dependency now?  Maybe we've supported Ruby 1.8.7 long enough now..

**Comment by matthutchinson** [comment]
Also, there is a whole bunch of new Rubocop issues, I think I will peg our Rubocop version in our gemspec, to avoid these cropping up every time someone issues a new PR.

**Comment by mroth** [comment]
I'm not opposed to dropping `1.8.7` support eventually if we gain convenience from it, but since I believe some Linux distros still ship with that as the default, it probably makes sense to know for certain we will want to take advantage of `>= 1.9.3` features other than saving 7 characters in an optional plugin, for the loss of reverse compatibility tradeoff to make sense.

(But yeah, we should definitely peg the Rubocop version to avoid the test spam. Good catch.)

**Comment by matthutchinson** [comment]
Agree, I'll give myself a TODO to see if I can breakdown which distro's still ship with 1.8.7 by default.  And I'll get around to dealing with Rubocop too.  @mrYakamoto thanks for your effort - but closing this PR for now.

**Pull request closed without merging**
