### PR TITLE
Add slack integration

### PR DESCRIPTION
**Pull request by yasakbulut**
# lol-slack
This PR adds a new plugin that handles image upload to slack; to share the awesomeness with friends, coworkers and envious nemeses.

The upload is done using the [Slack Web API File Upload](https://api.slack.com/methods/files.upload). The files are stored on slack, and posted to a channel/several channels specified in the configuration. 

Heavily inspired by (read: copied from) lol-yammer and uploldz.

## Configuration
lol-slack needs a valid user token in order to function. You can generate a personal token via the [Slack Web API](https://api.slack.com/web).
Additionally, you can specify in which channels or private groups to which the images should be posted. Simply enter a comma-separated list of channel IDs.
```
lolcommits --config -p slack

Configuring plugin: slack
enabled: true
Open the URL below and issue a token for your user:
https://api.slack.com/web
Enter the generated token below, then press enter: (e.g. xxxx-xxxxxxxxx-xxxx)
[User Token]
Enter a comma-seperated list of channel IDs to post images in, then press enter: (e.g. C1234567890,C1234567890)
[Channel ID(s)]
```

## Notes
* At the time of writing, the master branch had 5 RuboCop offenses, and 1 failed feature test (On My Machine:tm:). This branch does not increase those numbers (On My Machine:tm:)
* Suggestions, nitpickings and flame-wars are welcome

### CODE REVIEW

**Comment by tooluser** [comment]
This is fantastic!

**Comment by tooluser** [comment]
Any chance this'll get merged?

**Comment by matthutchinson** [comment]
I think i'll get a chance to look at it tomorrow, sorry for the delay.

**Comment by tooluser** [comment]
Hey, that's great! I was just worried it was dead or otherwise stale. Busy I can relate to... And once I have slack I can hook up the whole dept!

-- 
Joshua Marker
"Future site of beautiful San Andreas Canyon."

**Comment by matthutchinson** [comment]
Sorry, i'm "slack"ing on this I know, tomorrow night for sure :+1:

**Comment by tooluser** [comment]
OIC what you did there. ;-)

**Comment by matthutchinson** [comment]
Ok, I took a look and it all looks and works great.  The one thing that threw me was the need to pass a Channel ID (and not a channel name).  I might make this more clear in the config help text after merging, or calling [this endpoint](https://api.slack.com/methods/channels.list) to find channels by name first.

In any case, merging now, and will push a new point release out ASAP.  Sorry this took so long to review and merge and thanks for your contribution!

**Comment by matthutchinson** [comment]
FYI, I applied [this commit](https://github.com/mroth/lolcommits/commit/79c26f492e7c1859586e782ea8c640a5269654ba) after merging.

**Comment by tooluser** [comment]
This is like christmas morning!

**Comment by matthutchinson** [comment]
I've added [this feature request](https://github.com/mroth/lolcommits/issues/285) issue just now - so perhaps someone (or my future self) will get to it.

**Comment by yasakbulut** [comment]
Hey, thanks for your comments and the merge! I might take a look at [the feature request](https://github.com/mroth/lolcommits/issues/285) in the future, but don't count on it just yet =)

**Comment by matthutchinson** [comment]
Hi @yasakbulut 👋

So you may (or may not) have noticed that we [recently extracted](https://github.com/mroth/lolcommits/issues?utf8=✓&q=label%3Aarchitecture+label%3Aplugin+) all lolcommit plugins to external gems!

🏅 Since you contributed this slack plugin, I've added you (as an admin) to the new [lolcommits-slack](https://github.com/lolcommits/lolcommits-slack) repo.

Of course **you are under no obligation** to maintain this code or gem going forward. This is just a quick message to explain what has happened and give you the opportunity to take ownership again.

If you're interested in picking this up, **send me your email address** (to matt/at/hiddeloop.com) and I'll add you as a new gem owner (with publishing rights) [here](https://rubygems.org/gems/lolcommits-slack).

Otherwise I will continue to maintain the gem, and make sure things are kept up to date.

---

To get an idea of how gem plugins work, check out the `sample_plugin` [README](https://github.com/lolcommits/lolcommits-sample_plugin) / [RubyDocs](http://www.rubydoc.info/github/lolcommits/lolcommits-sample_plugin) or browse through [other plugin](https://github.com/lolcommits) code.

The main reasons for extraction were to:

* remove the ever-growing gem dependency list in the main lolcommits gem
* start to unify configuration code for plugins (common helpers, approaches to OAuth etc.)
* make lolcommit plugin development easier
* add more comprehensive plugin tests

That's it, any questions just let me know.

Happy coding!

Matt

**Pull request merged**
