### PR TITLE
feat: hipchat integration

### PR DESCRIPTION
**Pull request by Salzig**
HipChat Integration \o/

### CODE REVIEW

**Comment by Salzig** [comment]
There are some errors unrelated to my change. 

First with ** 1.9.3 **, which should break every newer build.
```
Gem::InstallError: term-ansicolor requires Ruby version >= 2.0.
Installing simplecov 0.12.0
An error occurred while installing term-ansicolor (1.4.0), and Bundler cannot
```

And then **2.0.0** and **2.3.0** which is maybe just a timing problem? At least i can't see how my change could produce this problem only with 2.0.0 and 2.3.0, but not with 2.1.7 and 2.2.4.
```
expected: 1
     got: 0
(compared using ==)
 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/lolcommits_steps.rb:160:in `/^there should be exactly (.*?) (jpg|gif|pid)s? in "(.*?)"$/'
features/lolcommits.feature:74:in `Then there should be exactly 1 pid in "~/.lolcommits/forked"'
Failing Scenarios:
cucumber features/lolcommits.feature:70 # Scenario: Capture doesnt break in forked mode
```

**Comment by matthutchinson** [comment]
Sorry for the later reply - i'll look into the 1.9.3 issue now.  The 'forked mode' pid tests are known to be a bit flakey and should pass on a re-run.

**Comment by matthutchinson** [comment]
[This PR](https://github.com/mroth/lolcommits/pull/321) should fix the 1.9.3 issue (and another with 2.1) - I'll merge it when green - I restarted your other failed builds with the forked issue and they passed OK

You can then rebase with upstream/master and your PR should pass.

**Comment by Salzig** [comment]
@matthutchinson done :)

**Comment by matthutchinson** [comment]
You'll need to add a require for this new file, in `lib/lolcommits.rb` along with the other plugins.  Other than that, this looks good to me.

**Comment by Salzig** [comment]
@matthutchinson good point, changed that.

**Comment by matthutchinson** [comment]
Great merging now 👍

**Comment by matthutchinson** [comment]
Hi @salzig 👋

So you may (or may not) have noticed that we [recently extracted](https://github.com/mroth/lolcommits/issues?utf8=✓&q=label%3Aarchitecture+label%3Aplugin+) all lolcommit plugins to external gems!

🏅 Since you contributed this hipchat plugin, I've added you (as an admin) to the new [lolcommits-hipchat](https://github.com/lolcommits/lolcommits-hipchat) repo.

Of course **you are under no obligation** to maintain this code or gem going forward. This is just a quick message to explain what has happened and give you the opportunity to take ownership again.

If you're interested in picking this up, **send me your email address** (to matt/at/hiddeloop.com) and I'll add you as a new gem owner (with publishing rights) [here](https://rubygems.org/gems/lolcommits-hipchat).

Otherwise I will continue to maintain the gem, and make sure things are kept up to date.

---

To get an idea of how gem plugins work, check out the `sample_plugin` [README](https://github.com/lolcommits/lolcommits-sample_plugin) / [RubyDocs](http://www.rubydoc.info/github/lolcommits/lolcommits-sample_plugin) or browse through [other plugin](https://github.com/lolcommits) code.

The main reasons for extraction were to:

* remove the ever-growing gem dependency list in the main lolcommits gem
* start to unify configuration code for plugins (common helpers, approaches to OAuth etc.)
* make lolcommit plugin development easier
* add more comprehensive plugin tests

That's it, any questions just let me know.

Happy coding!

Matt

**Pull request merged**
