### PR TITLE
Added animated capture for Windows

### PR DESCRIPTION
**Pull request by freehugs**
a6a1ba26fce

Using ffmpeg vfwcap to capture video.

### CODE REVIEW

**Comment by matthutchinson** [comment]
Looking into this PR now.. will test on a VM - there are a couple of conflicts given the latest changes on master.

**Comment by Ruxton** [comment]
Also `vfwcap` input is outdated, you should use the `dshow` input

https://trac.ffmpeg.org/wiki/Capture/Webcam
https://ffmpeg.org/ffmpeg-devices.html#dshow

**Comment by Ruxton** [comment]
Unrelated but worth noting, OSX & Linux could prob be switched to use ffmpeg capture too.

`avfoundation` input for OSX and `v4l2` input for linux

**Comment by theY4Kman** [comment]
We initially had some trouble getting dshow to capture correctly. It would drop frames, regardless of `-rtbufsize`. This was overcome by setting vcodec to `copy`... though, I'm not sure all capture devices can handle "copy". One other hurdle with dshow is it requires an explicit device name — there's no way to tell it to use the "default capture device". However, the devices could be [enumerated programmatically](https://trac.ffmpeg.org/wiki/DirectShow#Howtoprogrammaticallyenumeratedevices), so we could simply select the first one.

**Comment by matthutchinson** [comment]
So I've had a go at getting this to work on my Windows VM, and I have something that works and looks reasonable with `dshow` (using the `LOLCOMMITS_DEVICE` ENV or falling back to getting the device name "programmatically" 🤖). Also, the code in this PR assumes `seq` and `tr` commands are available on the Windows CMD line (they are not) - but I have a workaround for that too.  

If I can get it in decent shape I will l likely close this PR and issue a new one for animated capturing on Windows.

@Ruxton we could switch to ffmpeg for all platforms ... and ditch the embedded [VideoSnap](https://github.com/matthutchinson/videosnap) binary.  The reason I created/added that, was an attempt at removing the dependency on ffmpeg on OSX altogether. I'd planned to have VideoSnap generate the animated gif file through AV foundation, and eventually take single snaps too. Since I never got there, perhaps its best to drop it in favour of ffmpeg everywhere.

**Comment by matthutchinson** [comment]
Also, when using ffmpeg `vfwcap` as input, I get this dialog popping up in my VM... selecting Apply/OK seems to do nothing, and no capture is taken.  

screen shot 2017-08-04 at 21 20 46

**Comment by matthutchinson** [comment]
@theY4Kman is using `-vcodec copy` all I need to use? From the [docs](http://ffmpeg.org/ffmpeg.html#Stream-copy) it seems to avoid any encoding at all - I'll try it and see how it goes.. May need someone with a real PC and webcam to check this out... A VM may not cut it for testing purposes.

**Comment by matthutchinson** [comment]
Closing this PR in favour of [this](351), (sorry for the huge delay).

@freehugs many thanks for your contribution  👏 
I'll be sure to mention you in the next [CHANGELOG](https://github.com/mroth/lolcommits/blob/master/CHANGELOG.md) update.

**Pull request closed without merging**
